services:
  # Web application server
  queryjun:
    container_name: queryjun-deploy
    build:
      context: .
      dockerfile: ./Dockerfile.queryjun
    expose:
      - "8000"
    volumes:
      - ./docker_storage/log:/var/log/
    networks:
      - deploy-network
    depends_on:
      - postgres_solving
      - rabbitmq
    env_file:
      - ./.env/django-env
      - ./.env/postgres-solving-env
      - ./.env/rabbitmq-env

  # Web server
  nginx:
    container_name: nginx-deploy
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker_storage/nginx/access.log:/var/log/nginx/access.log
      - ./docker_storage/nginx/error.log:/var/log/nginx/error.log
    networks:
      - deploy-network
    depends_on:
      - queryjun

  # Postgres containe for executing queries
  postgres_solving:
    image: postgres:latest
    container_name: postgres-solving
    expose:
      - "5432"
    env_file:
      - ./.env/postgres-env
      - ./.env/postgres-solving-env
    shm_size: 128mb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./entrypoint.sh:/docker-entrypoint-intdb.d/entrypoint.sh
      - ./docker_storage/postgres:/var/lib/postgresql/data
    networks:
      - deploy-network
    entrypoint: ["/bin/bash", "/docker-entrypoint-intdb.d/entrypoint.sh"]

  # rabbitmq
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq-deploy
    expose:
      - "5672"
    env_file:
      - ./.env/rabbitmq-env
    volumes:
      - ./deploy-settings/rabbitmq/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./deploy-settings/rabbitmq/definitions.template.json:/etc/rabbitmq/definitions.template.json
      - ./docker_storage/rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker_storage/rabbitmq/data:/var/lib/rabbitmq
      - ./docker_storage/rabbitmq/logs:/var/log/rabbitmq
    networks:
      - deploy-network
    entrypoint: ["/bin/bash", "/usr/local/bin/entrypoint.sh"]

networks:
  deploy-network:
    driver: bridge