FROM nginx:latest

RUN apt-get update && apt-get install -y \
    net-tools \
    dnsutils \
    systemd \
    vim \
    curl \
    openssl

COPY ./nginx-settings/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
